# Generated by Django 3.1.7 on 2021-03-02 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('attedence', models.BooleanField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_name', models.CharField(max_length=50)),
                ('meeting_link', models.URLField()),
                ('start_time', models.TimeField(default='12:00:00')),
                ('end_time', models.TimeField(default='12:00:00')),
                ('date', models.DateField()),
                ('discription', models.TextField(max_length=500)),
                ('attendee', models.ManyToManyField(to='app.Attendee')),
            ],
        ),
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], default='None', max_length=50)),
                ('meet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.meeting')),
            ],
        ),
    ]
